# Generated by Django 4.2.5 on 2023-10-03 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255, verbose_name='name client')),
                ('lastNames', models.CharField(max_length=255, verbose_name='last names client')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adress', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='The phone number must be exactly 10 digits long.', regex='^\\d{10}$')])),
                ('cedula', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='The phone number must be exactly 11 digits long.', regex='^\\d{11}$')])),
                ('birthdate', models.DateField()),
            ],
            options={
                'ordering': ['names'],
            },
        ),
    ]
