# Generated by Django 4.2.5 on 2023-10-03 07:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appLogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('descriptions', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateIn', models.DateField(auto_now_add=True)),
                ('dateOut', models.DateField()),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('depth', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('totalVolume', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('isFragile', models.BooleanField()),
                ('totalWeight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'ordering': ['dateIn'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('depth', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('totalSpace', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('availableSpace', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('recordQuantity', models.PositiveIntegerField(default=0)),
                ('adress', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='isDeleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='client',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='RecordProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False, editable=False)),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appLogin.product')),
                ('idRecord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appLogin.record')),
            ],
            options={
                'ordering': ['idRecord'],
            },
        ),
        migrations.AddField(
            model_name='record',
            name='idClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appLogin.client'),
        ),
        migrations.AddField(
            model_name='record',
            name='idStore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appLogin.store'),
        ),
        migrations.AddField(
            model_name='record',
            name='products',
            field=models.ManyToManyField(through='appLogin.RecordProduct', to='appLogin.product'),
        ),
    ]
