# Generated by Django 4.2.5 on 2023-10-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLogin', '0002_product_record_store_client_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='lastNames',
            field=models.CharField(max_length=255, verbose_name='Last names'),
        ),
        migrations.AlterField(
            model_name='client',
            name='names',
            field=models.CharField(max_length=255, verbose_name='Names'),
        ),
        migrations.AlterUniqueTogether(
            name='recordproduct',
            unique_together={('idRecord', 'idProduct')},
        ),
    ]
