# Generated by Django 4.2.5 on 2023-10-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLogin', '0004_record_heightposition_record_widthposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='idSpace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
